create table
  public.catalog_items (
    id bigint generated by default as identity,
    name text not null,
    sku text null,
    quantity integer null,
    red_ml integer null,
    green_ml integer null,
    blue_ml integer null,
    dark_ml integer null,
    price integer null,
    constraint catalog_items_pkey primary key (id)
  ) tablespace pg_default;

  create table
  public.global_inventory (
    num_red_potions integer generated by default as identity,
    num_red_ml integer not null,
    gold integer null,
    num_blue_potions integer null,
    num_blue_ml integer null default 0,
    num_green_potions integer null default 0,
    num_green_ml integer null,
    constraint global_inventory_pkey primary key (num_red_potions)
  ) tablespace pg_default;

  create table
  public.carts (
    id bigint generated by default as identity,
    constraint carts_pkey primary key (id)
  ) tablespace pg_default;

  create table
  public.cart_items (
    id bigint generated by default as identity,
    item_id bigint null,
    quantity integer null,
    cart bigint null,
    constraint cart_items_pkey primary key (id),
    constraint cart_items_cart_fkey foreign key (cart) references carts (id) on delete cascade,
    constraint cart_items_item_id_fkey foreign key (item_id) references catalog_items (id)
  ) tablespace pg_default;